name: 'Post Run Action'
description: 'set post run script action'
author: 'https://github.com/srz-zumix'

inputs:
  post-run:
    description: 'post run script text'
    required: true

runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
