name: 'Post Run Action'
description: 'set post run script action'
author: 'https://github.com/srz-zumix'

inputs:
  post-run:
    description: 'post run script text'
    required: true
  shell:
    # Default : bash -e {0}
    # bash    : bash --noprofile --norc -eo pipefail {0}
    # custom  : e.g. `bash -l -ex {0}`
    description: 'custom shell command'
    default: ""

runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
